### ISSUE TITLE
[Bug] Editor Extensions Redux randomly downgrades SPH, VAB, Runway and/or LaunchPad to minimum level.

### ISSUE THREAD

**Issue by Monniasza** [linuxgurugamer/EditorExtensionsRedux#41]
KSP Version: 1.8.1
Mod Version: 3.4.1

To recreate:
* Go to SPH or VAB in science or sandbox mode
* Switch editors until either size, weight or complexity are limited.

Log: [KSP.log](https://github.com/linuxgurugamer/EditorExtensionsRedux/files/4499288/KSP.log)

**Comment by linuxgurugamer** [comment]
First, you need to provide the Player.log as well.
Second, you should post reports like this on the forum first, for the following reasons:

a. Since this is the very first time I've heard of this, it most likely is not a bug since this is an extremely popular mod and I would have heard about it before.
b. There are other people on the forum who can also help

Finally, after taking a quick look at the file you did provide, I see a lot of errors.  Also, you have so many mods installed that it is impossible to point to a single mod.  I counted over 135 different DLLs listed.

You need to reduce the number of mods to an absolute minimum, otherwise no one will be able to figure out anything
