### ISSUE TITLE
Visual icon for symmetry not updating in game. EEX 3.4.1.1 and KSP 1.9. 

### ISSUE THREAD

**Issue by Z28Tempest** [linuxgurugamer/EditorExtensionsRedux#42]
The visual icon for symmetry count and type (R/M 1,2,3,4...) is not updating in the game. Using EEX 3.4.1.1 and KSP 1.9. 
If I click the small window, stock modes will update. 
![EEX](https://user-images.githubusercontent.com/13287551/93426505-69eb9700-f879-11ea-9d5f-87d5440c4277.PNG)

**Comment by linuxgurugamer** [comment]
Then it sounds like something isn't installed properly, because it does work for me.
Please provide a log file for analysis, also, in the future, please post things like this in the forum thread before calling it a bug.  Here I'm the only one who responds, on the forum there are other people who might have replied much sooner

**Comment by Z28Tempest** [comment]
I tried copying the original EditorExtensionsRedux folder back into the GameData folder again, but the same problem. 
It works normally without the EEX folder. 
The log file has these messages in it: 
[ERR 20:44:00.476] ADDON BINDER: Cannot resolve assembly: EditorExtensionsRedux.XmlSerializers, Culture=neutral, PublicKeyToken=null
[EXC 20:44:00.858] FileNotFoundException: Could not load file or assembly 'ClickThroughBlocker, Version=0.1.9.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.

**Comment by linuxgurugamer** [comment]
Most definitely not installed properly.  You are missing the ClickThroughBlocker, which this mod depends on  You can ignore the XmlSerializers,it's a microsoft bug which isn't going to be fixed

**Comment by Z28Tempest** [comment]
I installed the newest ClickThroughBlocker version, and it causes the game to not load. Without it, the game runs normally.

**Comment by linuxgurugamer** [comment]
Then you have other issues, such as ToolbarController being up-to-date, SpaceTuxLibrary being up-to-date, etc.  Without a log file or anything else, can't help you..  I suggest you post on the forum, since this is an install issue.  The mod works on thousands of other systems, it has to be something in your install.

**Comment by Z28Tempest** [comment]
How many dependencies do I have to install?

**Comment by achieve3000** [comment]
Full details are here:

https://forum.kerbalspaceprogram.com/index.php?/topic/127378-19x-editor-extensions-redux-released-with-selectroot-merge-stripsymmetry-nooffsetlimits/

I also suggest that you use CKAN for your mods, it will take care of things like this automatically
